git commit -m

diff --git a/serv-if-up b/serv-if-up
--- a/serv-if-up
+++ b/serv-if-up
@@ -1,76 +1,210 @@
 #!/bin/bash
 
-# REDUNDANZ, depends on sh13lD
-# Restarts $webserver, $datenbank und $mta.
-###     WARNING:    DON'T EDIT ANYTHING BELOW       ###
-
-LANG="C";
+# version 0.01
+#REDUNDANZ
 
 		if [ ! $EUID = 0 ] ;
 	then
-		sudo "$0" ;
+		echo "USAGE: sudo shi3lD" ;
+		exit 0 ;
 else
+
+	if [[ "$(ps aux | grep -v grep | grep -v nano | grep shi3lD | awk '{print $2}' | wc -l) " -gt "1" ]] ;
+then
+
+LANG="C";
 
 countwarn="0" ;
 
-# temp folder
-			if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ;
-	then
-		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
-	else
-		tmpfolder="/tmp" ;
-fi
-# temp folder END
+PIDof=$(pgrep shi3lD) ;
+
+		if [[ "$PIDof" != '' ]] ;
+then
+
+nids="snort" ;
+
+antivirus="clamd" ;
 
 webserver="apache2" ;
+
 datenbank="mysql" ;
+
 mta="sendmail" ;
+
 mailer="sendmail" ;
+
 empty02='' ;
+
 nohomePartition="No Home Partition on this computer" ;
+
 WARN01="80" ;
+
 WARN02="85" ;
+
 PERCENTUSED01=$(df -h | grep -E /$ | awk '{ print $5 }' | sed -n 's/%//p') ;
+
 PERCENTUSED02=$(df -h | grep -E /home$ | awk '{ print $5 }' | sed -n 's/%//p') ;
+
 IFHOMEEXIST=$(df -h | grep -E /home$) && SIZEONHOME=$(df -h | grep -E /home$ | awk '{print $2}') ;
+
 SIZEON=$(df -h | grep -E /$ | awk '{ print $2 }') ;
+
 USEDON=$(df -h | grep -E /$ | awk '{ print $3 }') ;
+
 INODES=$(df -i | grep -E /$ | awk '{ print $2 }') ;
+
 FREEINODES=$(df -i | grep -E /$ | awk '{ print $4 }') ;
->| $tmpfolder/mailapache2status ;
->| $tmpfolder/mailsendmailstatus ;
->| $tmpfolder/mailmysqlstatus ;
+
+> /tmp/mailapache2status ;
+
+> /tmp/mailsendmailstatus ;
+
+> /tmp/mailmysqlstatus ;
 
 while true
 
 do
-        if [[ "$(netstat -an | grep LISTEN | grep :80 | awk '{print $4}' | tail -n1)" = '' ]];
+
+checknids=$(ps aux | grep -v grep | grep snort) ;
+
+sleep 0.5 ;
+
+        if [[ "$checknids" = '' ]];
 then
-	systemctl stop "$webserver".service ;
+	systemctl stop "$nids".service ;
+
 	sleep 1 ;
-	if systemctl start "$webserver".service ;
+
+	if systemctl start "$nids".service ;
 then
 
-echo -e "\n\n:: $webserver fails, but restartet successfully, you got an email ::\n" > /dev/pts/2 ;
-date > /dev/pts/2 ;
-systemctl status "$webserver".service >|$tmpfolder/mailapache2status ;
-cat << EOM | sendmail "$SUDO_USER"@localhost
+echo -e "\n\n:: $nids fails, but restartet successfully, you got an email ::\n" > /dev/pts/3 ;
+
+date > /dev/pts/3 ;
+
+systemctl status "$nids".service > /tmp/mailapache2status ;
+
+cat << EOM | mail "$SUDO_USER"@localhost
+
 Subject:"$webserver" restartet
-$(cat $tmpfolder/mailapache2status)
+
+$(cat /tmp/mailapache2status)
+
 EOM
 	else
 
-systemctl status "$webserver".service >|$tmpfolder/mailapache2status ;
-cat << EOM | sendmail "$SUDO_USER"@localhost
+systemctl status "$nids".service > /tmp/mailapache2status ;
+
+cat << EOM | mail "$SUDO_USER"@localhost
+
 Subject:"$webserver" cannot_restart
-$(cat $tmpfolder/mailapache2status)
+
+$(cat /tmp/mailapache2status)
+
 EOM
-echo -e "\n\n:: you got email, $webserver fails, cannot restart ::\n" > /dev/pts/2 ;
-date > /dev/pts/2 ;
+
+echo -e "\n\n:: you got email, $nids fails, cannot restart ::\n" > /dev/pts/3 ;
+
+date > /dev/pts/3 ;
 
 	fi
 fi
-        if [[ "$(netstat -an | grep LISTEN | grep :25 | awk '{print $4}' | tail -n1)" = '' ]];
+
+checkantivirus=$(ps aux | grep -v grep | grep clamd) ;
+
+sleep 2 ;
+
+        if [[ "$checkantivirus" = '' ]];
+then
+	systemctl stop "$antivirus".service ;
+
+	sleep 1 ;
+
+	if systemctl start "$antivirus".service ;
+then
+
+echo -e "\n\n:: $antivirus fails, but restartet successfully, you got an email ::\n" > /dev/pts/3 ;
+
+date > /dev/pts/3 ;
+
+systemctl status "$antivirus".service > /tmp/mailapache2status ;
+
+cat << EOM | mail "$SUDO_USER"@localhost
+
+Subject:"$webserver" restartet
+
+$(cat /tmp/mailapache2status)
+
+EOM
+	else
+
+systemctl status "$antivirus".service > /tmp/mailapache2status ;
+
+cat << EOM | mail "$SUDO_USER"@localhost
+
+Subject:"$webserver" cannot_restart
+
+$(cat /tmp/mailapache2status)
+
+EOM
+
+echo -e "\n\n:: you got email, $antivirus fails, cannot restart ::\n" > /dev/pts/3 ;
+
+date > /dev/pts/3 ;
+
+	fi
+fi
+
+checkport80=$(netstat -an | grep LISTEN | grep :80 | awk '{print $4}' | tail -n1) ;
+
+sleep 2 ;
+
+        if [[ "$checkport80" = '' ]];
+then
+	systemctl stop "$webserver".service ;
+
+	sleep 1 ;
+
+	if systemctl start "$webserver".service ;
+then
+
+echo -e "\n\n:: $webserver fails, but restartet successfully, you got an email ::\n" > /dev/pts/3 ;
+
+date > /dev/pts/3 ;
+
+systemctl status "$webserver".service > /tmp/mailapache2status ;
+
+cat << EOM | mail "$SUDO_USER"@localhost
+
+Subject:"$webserver" restartet
+
+$(cat /tmp/mailapache2status)
+
+EOM
+	else
+
+systemctl status "$webserver".service > /tmp/mailapache2status ;
+
+cat << EOM | mail "$SUDO_USER"@localhost
+
+Subject:"$webserver" cannot_restart
+
+$(cat /tmp/mailapache2status)
+
+EOM
+
+echo -e "\n\n:: you got email, $webserver fails, cannot restart ::\n" > /dev/pts/3 ;
+
+date > /dev/pts/3 ;
+
+	fi
+fi
+
+checkport25=$(netstat -an | grep LISTEN | grep :25 | awk '{print $4}' | tail -n1) ;
+
+sleep 2 ;
+
+        if [[ "$checkport25" = '' ]];
 then
 
 checkprog2=$(whereis "$mta" | awk '{print $2}') ;
@@ -78,31 +212,53 @@ checkprog2=$(whereis "$mta" | awk '{print $2}') ;
 	if [[ -e $checkprog2 ]] ;
 then
 	systemctl stop "$mta".service
-	sleep 1 ;
-        systemctl start "$mta".service >|$tmpfolder/mailsendmailstatus ;
-        systemctl status "$mta".service >>$tmpfolder/mailsendmailstatus ;
-	echo "$?" >>$tmpfolder/mailsendmailstatus ;
-	sleep 1 ;
-cat << EOM | sendmail "$SUDO_USER"@localhost
+
+sleep 1 ;
+
+        systemctl start "$mta".service > /tmp/mailsendmailstatus ;
+
+        systemctl status "$mta".service >> /tmp/mailsendmailstatus ;
+
+	echo "$?" >> /tmp/mailsendmailstatus ;
+
+sleep 1 ;
+
+cat << EOM | mail "$SUDO_USER"@localhost
+
 Subject:"$mta" restartet
-$(cat $tmpfolder/mailsendmailstatus)
+
+$(cat /tmp/mailsendmailstatus)
+
 EOM
-echo -e "\n\n:: $mta is accepting connections again, you got an email ::\n" > /dev/pts/2 ;
-date > /dev/pts/2 ;
+
+echo -e "\n\n:: $mta is accepting connections again, you got an email ::\n" > /dev/pts/3 ;
+
+date > /dev/pts/3 ;
 
 	else
 
-date "+Start Attempt, Failure Time: %H.%M" >|$tmpfolder/mailsendmailstatus ;
-cat << EOM | sendmail "$SUDO_USER"@localhost
+	date "+Start Attempt, Failure Time: %H.%M" > /tmp/mailsendmailstatus ;
+
+cat << EOM | mail "$SUDO_USER"@localhost
+
 Subject:"$mta" cannot_restart
-$(cat $tmpfolder/mailsenmailfail)
+
+$(cat /tmp/mailsenmailfail)
+
 EOM
-echo -e "\n\n:: you got email, $mta cannot restart ::\n" > /dev/pts/2 ;
-date > /dev/pts/2 ;
+
+echo -e "\n\n:: you got email, $mta cannot restart ::\n" > /dev/pts/3 ;
+
+date > /dev/pts/3 ;
 
 	fi
 fi
-        if [[ "$(netstat -an | grep LISTEN | grep :3306 | awk '{print $4}' | tail -n1)" = '' ]];
+
+checkport3306=$(netstat -an | grep LISTEN | grep :3306 | awk '{print $4}' | tail -n1) ;
+
+sleep 2 ;
+
+        if [[ "$checkport3306" = '' ]];
 then
 
 checkprog3=$(whereis "$datenbank" | awk '{print $2}') ;
@@ -110,30 +266,47 @@ checkprog3=$(whereis "$datenbank" | awk '{print $2}') ;
 	if [[ -e $checkprog3 ]] ;
 then
 	/etc/init.d/"$datenbank" stop ;
-	sleep 1 ;
-        /etc/init.d/"$datenbank" start >|$tmpfolder/mailmysqlstatus ;
-        /etc/init.d/"$datenbank" status >>$tmpfolder/mailmysqlstatus ;
-	echo "$?" >>$tmpfolder/mailmysqlstatus ;
+
 sleep 1 ;
-cat << EOM | sendmail "$SUDO_USER"@localhost
+        /etc/init.d/"$datenbank" start > /tmp/mailmysqlstatus ;
+
+        /etc/init.d/"$datenbank" status >> /tmp/mailmysqlstatus ;
+
+	echo "$?" >> /tmp/mailmysqlstatus ;
+
+sleep 1 ;
+
+cat << EOM | mail "$SUDO_USER"@localhost
+
 Subject:"$datenbank" restartet
-$(cat $tmpfolder/mailmysqlstatus)
+
+$(cat /tmp/mailmysqlstatus)
+
 EOM
-echo -e "\n\n:: $datenbank is accepting connections again, you got an email ::\n" > /dev/pts/2 ;
-date > /dev/pts/2 ;
+
+echo -e "\n\n:: $datenbank is accepting connections again, you got an email ::\n" > /dev/pts/3 ;
+
+date > /dev/pts/3 ;
 
 	else
 
-date "+Start Attempt, Failure Time: %H.%M" >|$tmpfolder/mailmysqlstatus ;
+	date "+Start Attempt, Failure Time: %H.%M" > /tmp/mailmysqlstatus ;
+
 cat << EOM | "$datenbank" "$SUDO_USER"@localhost
+
 Subject:$datenbank failure.
-$(cat $tmpfolder/mailmysqlstatus)
+
+$(cat /tmp/mailmysqlstatus )
+
 EOM
-echo -e "\n\n:: you got email, $datenbank cannot restart ::\n" > /dev/pts/2 ;
-date > /dev/pts/2 ;
+
+echo -e "\n\n:: you got email, $datenbank cannot restart ::\n" > /dev/pts/3 ;
+
+date > /dev/pts/3 ;
 
 	fi
 fi
+
 
 if [[ "$WARN01" -lt "$PERCENTUSED01" ]] || [[ "$WARN02" -lt "$PERCENTUSED02" ]] && [[ "$countwarn" = '0' ]] ;
 
@@ -152,32 +325,63 @@ echo "";
 fi
 
 countwarn=1 ;
-cat << EOM | sendmail "$SUDO_USER"@localhost
+
+cat << EOM | mail "$SUDO_USER"@localhost
+
 Subject:running_out_of_disk_space
+
 _________________________________________________
 /
+
+
 redundanz: On host $(uname -n) :: ;
+
 Warn percentage on /: $WARN01 %
+
 Used percentage on the root /: $PERCENTUSED01
+
 Inodes on host $(uname -n): $INODES
+
 Size on /: $SIZEON GB
+
 Used Inodes on /: $USEDON .
+
 Free Inodes on host $(uname -n): $FREEINODES
+
+
+
 _________________________________________________
 /home
+
+
 Warn percentage on /home: $WARN02 %
+
 Used percentage on /home: $PERCENTUSED02
+
 Size on /home: $SIZEONHOME GB
+
 EOM
-echo -e "\n\n::WARNING:: your over $WARN01 % or $WARN02 %, you got mail::\n" > /dev/pts/2 ;
-date > /dev/pts/2 ;
+
+echo -e "\n\n::WARNING:: your over $WARN01 % or $WARN02 %, you got mail::\n" > /dev/pts/3 ;
+
+date > /dev/pts/3 ;
 
 fi
 
 done
 
-rm -f $tmpfolder/mailapache2status ;
-rm -f $tmpfolder/mailsendmailstatus ;
-rm -f $tmpfolder/mailmysqlstatus ;
+rm -f /tmp/mailapache2status ;
+
+rm -f /tmp/mailsendmailstatus ;
+
+rm -f /tmp/mailmysqlstatus ;
+
+else
+
+killall serv-if-up.sh ;
+
+fi
+
+fi
 
 fi
